# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Graphs and networks in FEniCSx
author: Jørgen S. Dokken
logo: "docs/logo.png"
copyright: "2025"

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: cache
  timeout: 1800

only_build_toc_files: true

# Information about where the book exists on the web
repository:
  url: https://github.com/scientificcomputing/networks_fenicsx # Online location of your book

html:
  use_issues_button: true
  use_repository_button: true
  extra_footer: |
    <div>
        This software package has been developed by Jørgen S. Dokken while employed at Simula Research Laboratory.
        It is licensed under the MIT License. The work has been funded by the Wellcome Trust, grant number 313298/Z/24/Z.
    </div>
bibtex_bibfiles:
  - docs/references.bib

parse:
  myst_enable_extensions:
    - amsmath
    - dollarmath
    - linkify
    - html_image

sphinx:
  extra_extensions:
    - "sphinx.ext.autodoc"
    - "sphinx.ext.intersphinx"
    - "sphinx_codeautolink"
    - "sphinx.ext.napoleon"
    - "sphinx.ext.viewcode"

  config:
    codeautolink_concat_default: True
    intersphinx_mapping:
      basix: ["https://docs.fenicsproject.org/basix/v0.10.0/python/", null]
      ffcx: ["https://docs.fenicsproject.org/ffcx/v0.10.0/", null]
      ufl: ["https://docs.fenicsproject.org/ufl/2025.2.0.post0/", null]
      dolfinx: ["https://docs.fenicsproject.org/dolfinx/v0.10.0/python", null]
      petsc4py: ["https://petsc.org/release/petsc4py", null]
      mpi4py: ["https://mpi4py.readthedocs.io/en/stable", null]
      numpy: ["https://numpy.org/doc/stable/", null]
      pyvista: ["https://docs.pyvista.org/", null]
      packaging: ["https://packaging.pypa.io/en/stable/", null]
      matplotlib: ["https://matplotlib.org/stable/", null]
      scipy: ["https://docs.scipy.org/doc/scipy/", null]
      networkx: ["https://networkx.org/documentation/stable/", null]

    html_last_updated_fmt: "%b %d, %Y"
    html_theme_options:
      navigation_with_keys: false

    nb_custom_formats:
      .py:
        - jupytext.reads
        - fmt: py

exclude_patterns: [".pytest_cache/*"]