name: Build documentation with jupyter-book

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
  workflow_call:

  workflow_dispatch:
env:
  # Directory that will be published on github pages
  PUBLISH_DIR: ./docs/_build/html

jobs:

  build-docs:
    name: Test on ${{ matrix.label }}
    runs-on: ubuntu-latest
    container: ghcr.io/fenics/dolfinx/dolfinx:${{ matrix.label }}
    strategy:
      fail-fast: false
      matrix:
        label: [
          "stable",
          "nightly"
        ]
    env:
      PUBLISH_DIR: ./docs/_build/html
      PYVISTA_OFF_SCREEN: false
      PYVISTA_JUPYTER_BACKEND: "html"

    steps:
      - name: Checkout
        uses: actions/checkout@v5


      - name: Install dependencies
        run: python3 -m pip install ".[docs]"

      - name: Build docs
        run: 	jupyter book build --keep-going docs


      - name: Upload artifact
        uses: actions/upload-artifact@v5
        with:
          path: ${{ env.PUBLISH_DIR }}
          name: ${{ matrix.label }}-docs
