name: Test package

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:
  workflow_call:

jobs:
  test-code:
    name: Test on ${{ matrix.label }}
    runs-on: ubuntu-latest
    container: ghcr.io/fenics/dolfinx/dolfinx:${{ matrix.label }}
    env:
      DEB_PYTHON_INSTALL_LAYOUT: deb_system

    strategy:
      fail-fast: false
      matrix:
        label: [
          "stable",
          "nightly"
        ]


    steps:
      - uses: actions/checkout@v5

      - name: Update pip
        run: python3 -m pip install --upgrade pip

      - name: Install package
        run: |
          python3 -m pip install .[test,demos] --no-build-isolation --check-build-dependencies

      - name: Run tests
        working-directory: tests
        run: python3 -m pytest -vxs

      - name: Run tests in parallel
        working-directory: tests
        run: mpiexec -n 4 python3 -m pytest -v -m "not serial"

      - name: Run demos
        working-directory: demos
        run: pytest . -sv 
